export const FETCH_COCKTAIL_START="FETCH_COCKTAIL_START";
export const FETCH_COCKTAIL_SUCCESS="FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAIL_FAIL="FETCH_COCKTAIL_FAIL";
export const GET_SINGLECOCKTAIL_START="GET_SINGLECOCKTAIL_START";
export const GET_SINGLECOCKTAIL_SUCCESS="GET_SINGLECOCKTAIL_SUCCESS";
export const GET_SINGLECOCKTAIL_FAIL="GET_SINGLECOCKTAIL_FAIL";